# Generated by Django 6.0 on 2026-01-08 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comment"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="posts_comme_post_id_94ac6b_idx",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
