# Generated by Django 6.0 on 2025-12-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profile_image_profile_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="profiles/default-cover.jpg",
                null=True,
                upload_to="profiles/covers/",
            ),
        ),
    ]
