# Generated by Django 6.0 on 2026-01-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_cover_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="profiles/default-cover.png",
                null=True,
                upload_to="profiles/covers/",
            ),
        ),
    ]
